name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Java JDK 25 aufsetzen
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Node.js aufsetzen
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Frontend Dependencies installieren
        working-directory: ./frontend
        run: npm ci

      - name: Next.js Static Website generieren
        working-directory: ./frontend
        run: npm run build

      - name: Static Files nach Java Resources kopieren
        run: |
          mkdir -p backend/src/main/resources/static/glassbox
          rm -rf backend/src/main/resources/static/glassbox/*
          cp -r frontend/out/* backend/src/main/resources/static/glassbox
      

      - name: Repository-Namen in Kleinbuchstaben umwandeln
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Java App bauen (Maven)
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests


      - name: Login bei Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build und Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
